# Setup
title:            Aaron Abraham
tagline:          ''
description:      'University of Waterloo Software Engineering student'
url:              https://aaronabraham311.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Aaron Abraham'
  url:            https://aaronabraham.ca

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
